baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "hoscanoa.github.io" # the base hostname & protocol for your site.

paginate: 6 #articles per page
paginate_path: /blog/page:num #makes pagination working

# header text
title: Hoscanoa Serializando 2.0
header: Matemático, programador apasionado de C/C++, Java, Python y Javascript. Fotógrafo aficionado y constructor de cometas.

# for welcome page
# to replace image go to index.html
email:
  address: "hoscanoa@gmail.com"
  text: "hoscanoa (at) gmail.com"

# disqus comment
disqus:
    shortname: "test" #your disqus comment short name

# google analytics
google:
    tracking-id: "UA-136771046-1" #your tracking id here

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"

permalink: /posts/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
